name: Dadfat
favicon: null
layout_spectrum: 0.3189964
typography_spectrum: 0.37043
title: Dad Fat
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f7f8'
    - '#dae2ef'
    - '#4072af'
    - '#102d4d'
    - '#254a78'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
