name: Dadfat
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37043
title: Dad Fat. Where love handles are welcomed.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdc0'
    - '#9296b1'
    - '#16211d'
    - '#095000'
    - '#c37859'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.670952906133607
purpose: []
