name: Dadfat
favicon: null
layout_spectrum: 0.38243
typography_spectrum: 0.947912520263344
title: Dad Fat. Where love handles are welcomed.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.670952906133607
purpose: []
